---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xallowpublicdomains.v1.az.composite.scc.allianz.io
  annotations: 
    docs.allianz.io/description: |
      This resource configures application firewall rules to allow specific public domains
      or subdomains in Azure firewall. It enables controlled
      access to external services while maintaining security boundaries.
    docs.allianz.io/usecases: |
      - Allowing access to specific external APIs or services through Azure firewall
      - Configuring domain-based network access rules for applications
      - Managing whitelist of permitted public domains for outbound traffic
    docs.allianz.io/advantages: |
      - Provides granular control over external domain access
      - Maintains security while enabling necessary external connectivity
    docs.allianz.io/deendencies: |
      - dedicatedsubscription.v1.az.composite.scc.allianz.io
      - dedicatedvnet.v1.az.composite.scc.allianz.io
    docs.allianz.io/namingConvention: |
      There is no specific naming convention, as these rules are created directly in Azure Firewall.
    docs.allianz.io/tags: azure, firewall, domains, network-security
    docs.allianz.io/frontEndName: "Azure Application Firewall: Allow Specific Public Domain"
spec:
  group: v1.az.composite.scc.allianz.io
  defaultCompositeDeletePolicy: Foreground
  names:
    kind: XAllowPublicDomain
    plural: xallowpublicdomains
    singular: xallowpublicdomain
  claimNames:
    kind: AllowPublicDomain
    plural: allowpublicdomains
    singular: allowpublicdomain
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: |
                Defines the desired configuration for allowing public domains through Azure firewall.
                Requires domains list, networkName, and accountName for proper firewall rule creation.
              required: [domains, networkName, accountName]
              properties:
                domains:
                  description: |
                    domains: List of domains or subdomains that should be allowed through the firewall.
                    The name value should have the format. Allowed examples: "example.com", "*.subdomain.example.com", "api.service.com"
                    Restricted examples: "*.com", "*example.com", "*com" (overly broad patterns)
                  type: array
                  items:
                    type: string
                    allOf:
                      - not:
                          pattern: ^\*[a-zA-Z]{2,}$|^\*\.[a-zA-Z]{2,}$|^\*[a-zA-Z0-9-]+\.[a-zA-Z]{2,}$
                      - pattern: ^\*?\.?[a-zA-Z0-9][a-zA-Z0-9.-]*[a-zA-Z0-9]$
                networkName:
                  description: 'networkName: Name of the Network managed resource where the Azure firewall domain rules will be applied. This field is immutable - to update it, delete the existing claim and reapply a new one.'
                  type: string
                  x-kubernetes-validations:
                    - message: The name of a network managed resource remains permanent
                        and cannot be altered once submitted; otherwise, you need
                        to delete the existing claim and resubmit it, which will result
                        in the recreation of the rule.
                      rule: self == oldSelf
                accountName:
                  description: 'accountName: Name of the Azure subscription account where the virtual network is created. This field is immutable - to update it, delete the existing claim and reapply a new one.'
                  type: string
                  x-kubernetes-validations:
                    - message: The name of a account managed resource remains permanent
                        and cannot be altered once submitted; otherwise, you need
                        to delete the existing claim and resubmit it, which will result
                        in the recreation of the rule.
                      rule: self == oldSelf
            status:
              type: object
              description: |
                Contains information about the firewall rule creation and blob storage details.
                Fields are populated by automation after successful rule deployment.
              properties:
                blobLocation:
                  description: 'blobLocation: Azure storage location where firewall rule configuration is stored'
                  type: string
                blobContent:
                  description: 'blobContent: Serialized content of the firewall rule configuration blob'
                  type: string
